import { DUNGEON_ASSET_MANIFEST } from './asset-manifest.js';
import { renderMoonEclipseMap } from './tile-renderer.js';
const MAP=['##########','#........#','#........#','#...##...#','#........#','#......>.#','##########'].map(row=>[...row]);
const state={gridX:1,gridY:1,pixelX:1,pixelY:1,direction:'down',actionState:'idle',isMoving:false,buffer:null};
const dirs={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}};
const canvas=document.querySelector('#dungeon-canvas'),ctx=canvas.getContext('2d'),mini=document.querySelector('#minimap-canvas'),mctx=mini.getContext('2d');
const debug=document.querySelector('#debug'),log=document.querySelector('#log-text');
const sprites={};
for(const direction of DUNGEON_ASSET_MANIFEST.luna.directions){sprites[direction]=DUNGEON_ASSET_MANIFEST.luna.actions.walking.framesByDirection[direction].map(src=>{const image=new Image();image.src=src;image.addEventListener('load',render);return image})}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);mini.width=68;mini.height=68;render()}
function canMoveTo(x,y){return MAP[y]?.[x]&&MAP[y][x]!=='#'}
function requestMove(direction){state.direction=direction;if(state.isMoving){state.buffer=direction;updateDebug();return}const d=dirs[direction],tx=state.gridX+d.x,ty=state.gridY+d.y;if(!canMoveTo(tx,ty)){log.textContent='壁に行く手を阻まれた。';updateDebug();render();return}state.isMoving=true;state.actionState='walking';const sx=state.gridX,sy=state.gridY,start=performance.now(),duration=150;function step(now){const t=Math.min((now-start)/duration,1),e=1-(1-t)*(1-t);state.pixelX=sx+(tx-sx)*e;state.pixelY=sy+(ty-sy)*e;render();if(t<1)return requestAnimationFrame(step);state.gridX=tx;state.gridY=ty;state.pixelX=tx;state.pixelY=ty;state.isMoving=false;state.actionState='idle';log.textContent=`(${tx}, ${ty}) へ移動した。`;updateDebug();const next=state.buffer;state.buffer=null;if(next)requestMove(next)}requestAnimationFrame(step)}
function render(){const w=canvas.clientWidth,h=canvas.clientHeight,tile=Math.floor(Math.min(w/8,h/6)),ox=w/2-state.pixelX*tile-tile/2,oy=h/2-state.pixelY*tile-tile/2;ctx.clearRect(0,0,w,h);ctx.fillStyle='#02050b';ctx.fillRect(0,0,w,h);renderMoonEclipseMap(ctx,MAP,ox,oy,tile);const cx=w/2,cy=h/2;ctx.fillStyle='rgba(56,189,248,.25)';ctx.beginPath();ctx.ellipse(cx,cy+tile*.34,tile*.3,tile*.12,0,0,Math.PI*2);ctx.fill();const list=sprites[state.direction],frame=state.actionState==='walking'?Math.floor(performance.now()/90)%list.length:0,image=list[frame];if(image?.complete&&image.naturalWidth){const sw=tile*1.08,sh=sw*(DUNGEON_ASSET_MANIFEST.luna.frameSize.height/DUNGEON_ASSET_MANIFEST.luna.frameSize.width);ctx.imageSmoothingEnabled=false;ctx.drawImage(image,cx-sw/2,cy+tile*.48-sh,sw,sh)}else{ctx.fillStyle='#dbeafe';ctx.fillRect(cx-tile*.2,cy-tile*.3,tile*.4,tile*.65)}renderMini()}
function renderMini(){const tw=mini.width/MAP[0].length,th=mini.height/MAP.length;mctx.clearRect(0,0,mini.width,mini.height);MAP.forEach((row,y)=>row.forEach((cell,x)=>{mctx.fillStyle=cell==='#'?'#101827':'#42516a';mctx.fillRect(x*tw,y*th,tw,th)}));mctx.fillStyle='#f6d66f';mctx.beginPath();mctx.arc((state.gridX+.5)*tw,(state.gridY+.5)*th,3,0,Math.PI*2);mctx.fill()}
function updateDebug(){debug.innerHTML=`X: ${state.gridX} / Y: ${state.gridY}<br>Direction: ${state.direction}<br>State: ${state.actionState}`}
document.querySelectorAll('[data-dir]').forEach(button=>button.addEventListener('pointerdown',()=>requestMove(button.dataset.dir)));
document.querySelector('#wait').addEventListener('click',()=>{state.actionState='idle';log.textContent='その場で待機した。';updateDebug()});
document.querySelector('#map-toggle').addEventListener('click',()=>document.querySelector('#minimap').classList.toggle('hidden'));
addEventListener('keydown',event=>{const map={ArrowUp:'up',w:'up',W:'up',ArrowDown:'down',s:'down',S:'down',ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right'},dir=map[event.key];if(dir){event.preventDefault();requestMove(dir)}});
addEventListener('resize',resize);resize();updateDebug();
